version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "05:00"
    timezone: "UTC"
  # Because we only do this weekly, allow for many to be created.
  open-pull-requests-limit: 20
