minVersion: 0.23.1
changelogPolicy: auto
targets:
  - name: github
  - name: gh-pages
  - name: registry
    apps:
      app:symbolicator:
        urlTemplate: https://downloads.sentry-cdn.com/symbolicator/{{version}}/{{file}}
        includeNames: /^symbolicator-.*$/i
  - name: gcs
    bucket: sentry-sdk-assets
    includeNames: /^symbolicator-.*$/
    paths:
      - path: /symbolicator/{{version}}/
        metadata:
          cacheControl: public, max-age=2592000
      - path: /symbolicator/latest/
        metadata:
          cacheControl: public, max-age=600
  - id: release
    name: docker
    source: us.gcr.io/sentryio/symbolicator
    target: getsentry/symbolicator
  - id: latest
    name: docker
    source: us.gcr.io/sentryio/symbolicator
    target: getsentry/symbolicator
    targetFormat: '{{{target}}}:latest'
requireNames:
  - /^gh-pages.zip$/
  - /^symbolicator-Darwin-universal$/
  - /^symbolicator-Linux-x86_64$/
  - /^symbolicator-Linux-x86_64-debug.zip$/
  - /^symbolicator-aarch64-apple-darwin-debug.zip$/
  - /^symbolicator-x86_64-apple-darwin-debug.zip$/
  - /^symsorter-Darwin-universal$/
  - /^symsorter-Linux-x86_64$/
  - /^symsorter-Windows-x86_64\.exe$/
  - /^wasm-split-Darwin-universal$/
  - /^wasm-split-Linux-x86_64$/
  - /^wasm-split-Windows-x86_64\.exe$/
