site_name: Sentry Symbolicator
repo_url: https://github.com/getsentry/symbolicator
site_url: https://getsentry.github.io/symbolicator
site_author: Sentry
theme:
  name: material
  logo: static/icon.png
markdown_extensions:
  - tables
  - codehilite
extra_css:
  - '_css/extra.css'
nav:
  - index.md
  - Advanced:
    - advanced/background-and-principles.md
    - advanced/system-architecture.md
    - advanced/caching.md
    - advanced/shared-cache.md
    - advanced/symbol-lookup.md
    - advanced/symbol-server-compatibility.md
    - advanced/source-bundles.md
  - API:
    - api/index.md
    - api/minidump.md
    - api/symbolication.md
    - api/applecrashreport.md
    - api/response.md
    - api/proxy.md
