format_version: 10
pipelines:
  deploy-symbolicator-next-monitor:
    display_order: 2
    environment_variables:
      SENTRY_REGION: monitor
    group: symbolicator-next
    lock_behavior: unlockWhenFinished
    materials:
      deploy-symbolicator-next-us-pipeline-complete:
        pipeline: deploy-symbolicator-next-us
        stage: pipeline-complete
      symbolicator_repo:
        branch: master
        destination: symbolicator
        git: git@github.com:getsentry/symbolicator.git
        shallow_clone: true
    stages:
      - checks:
          environment_variables:
            GITHUB_TOKEN: '{{SECRET:[devinfra-github][token]}}'
          fetch_materials: true
          jobs:
            checks:
              elastic_profile_id: symbolicator
              tasks:
                - script: |
                    ##!/bin/bash

                    /devinfra/scripts/checks/githubactions/checkruns.py \
                      getsentry/symbolicator \
                      ${GO_REVISION_SYMBOLICATOR_REPO} \
                      'Tests' \
                      'Sentry-Symbolicator Tests'
                - script: |
                    ##!/bin/bash

                    /devinfra/scripts/checks/googlecloud/checkcloudbuild.py \
                      ${GO_REVISION_SYMBOLICATOR_REPO} \
                      sentryio \
                      "us.gcr.io/sentryio/symbolicator"
              timeout: 1200
      - deploy_canary:
          approval:
            type: manual
          fetch_materials: true
          jobs:
            create_sentry_release:
              elastic_profile_id: symbolicator
              environment_variables:
                ENVIRONMENT: canary
                SENTRY_AUTH_TOKEN: '{{SECRET:[devinfra-temp][symbolicator_sentry_auth_token]}}'
                SENTRY_URL: https://sentry.my.sentry.io/
              tasks:
                - script: |
                    ##!/bin/bash

                    ./symbolicator/scripts/create-sentry-release "${GO_REVISION_SYMBOLICATOR_REPO}" "${ENVIRONMENT}"
              timeout: 1200
            deploy:
              elastic_profile_id: symbolicator
              environment_variables:
                LABEL_SELECTOR: service=symbolicator,deploy_if_canary=true
              tasks:
                - script: |
                    ##!/bin/bash

                    eval $(/devinfra/scripts/regions/project_env_vars.py --region="${SENTRY_REGION}")
                    /devinfra/scripts/k8s/k8stunnel
                    /devinfra/scripts/k8s/k8sdeploy.py \
                      --type="statefulset" \
                      --label-selector="${LABEL_SELECTOR}" \
                      --image="us.gcr.io/sentryio/symbolicator:${GO_REVISION_SYMBOLICATOR_REPO}" \
                      --container-name="symbolicator" \
                      --container-name="cleanup"
              timeout: 1200
      - deploy_primary:
          approval:
            type: manual
          fetch_materials: true
          jobs:
            create_sentry_release:
              elastic_profile_id: symbolicator
              environment_variables:
                ENVIRONMENT: production
                SENTRY_AUTH_TOKEN: '{{SECRET:[devinfra-temp][symbolicator_sentry_auth_token]}}'
                SENTRY_URL: https://sentry.my.sentry.io/
              tasks:
                - script: |
                    ##!/bin/bash

                    ./symbolicator/scripts/create-sentry-release "${GO_REVISION_SYMBOLICATOR_REPO}" "${ENVIRONMENT}"
              timeout: 1200
            deploy:
              elastic_profile_id: symbolicator
              environment_variables:
                LABEL_SELECTOR: service=symbolicator
              tasks:
                - script: |
                    ##!/bin/bash

                    eval $(/devinfra/scripts/regions/project_env_vars.py --region="${SENTRY_REGION}")
                    /devinfra/scripts/k8s/k8stunnel
                    /devinfra/scripts/k8s/k8sdeploy.py \
                      --type="statefulset" \
                      --label-selector="${LABEL_SELECTOR}" \
                      --image="us.gcr.io/sentryio/symbolicator:${GO_REVISION_SYMBOLICATOR_REPO}" \
                      --container-name="symbolicator" \
                      --container-name="cleanup"
              timeout: 1200
      - pipeline-complete:
          approval:
            allow_only_on_success: true
            type: success
          jobs:
            pipeline-complete:
              tasks:
                - exec:
                    command: true
