x-sentry-service-config:
  version: 0.1
  service_name: symbolicator
  dependencies:
    symbolicator:
      description: A symbolication service for native stacktraces and minidumps with symbol server support
  modes:
    default: [symbolicator]

services:
  symbolicator:
    image: ghcr.io/getsentry/symbolicator:nightly
    volumes:
      - symbolicator-data:/data
      - type: bind
        read_only: true
        source: ./symbolicator
        target: /etc/symbolicator
    command: ["run", "--config", "/etc/symbolicator/config.yml"]
    ports:
      - 127.0.0.1:3021:3021
    networks:
      - devservices
    extra_hosts:
      - host.docker.internal:host-gateway # Allow host.docker.internal to resolve to the host machine
    labels:
      - orchestrator=devservices
    restart: unless-stopped

volumes:
  symbolicator-data:

networks:
  devservices:
    name: devservices
    external: true
