#!/bin/bash
set -eu
# Required environment variables:
#   SENTRY_AUTH_TOKEN: Sentry auth token (https://sentry.io/settings/account/api/auth-tokens/)

VERSION="${1:-}"
ENVIRONMENT="${2:-}"
# GITHUB_PROJECT="getsentry/symbolicator"
export SENTRY_ORG="sentry"
export SENTRY_PROJECT="symbolicator"

if [ -z "${VERSION}" ]; then
  echo 'No version specified' && exit 1
fi


if [ -z "${SENTRY_AUTH_TOKEN:-}" ]; then
  echo 'No Sentry auth token found' && exit 1
fi

sentry-cli --version

echo 'Pulling debug information...'
gsutil cp \
  "gs://dicd-team-devinfra-cd--symbolicator/difs/${VERSION}/symbolicator-*-debug.zip" \
  "gs://dicd-team-devinfra-cd--symbolicator/difs/${VERSION}/symbolicator-*.src.zip" \
  .

echo 'Uploading debug information and source bundle...'
sentry-cli upload-dif ./symbolicator-*-debug.zip ./symbolicator-*.src.zip

echo 'Creating a new deploy in Sentry...'
sentry-cli releases new "${VERSION}"
# NOTE: linking commits requires a valid GitHub integration in Sentry4Sentry, which we don't have.
# sentry-cli releases set-commits "${VERSION}" --commit "${GITHUB_PROJECT}@${VERSION}"
sentry-cli releases deploys "${VERSION}" new -e "${ENVIRONMENT}"
sentry-cli releases finalize "${VERSION}"
echo 'Deploy created.'
