name: "Danger"
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  build:
    name: Changelogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/danger
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
