name: Release Versioned Images

on:
  release:
    types: [prereleased, released]

permissions:
  contents: read
  packages: write

jobs:
  release-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release version
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/getsentry/symbolicator:${{ github.ref_name }} \
            ghcr.io/getsentry/symbolicator:${{ github.sha }}

      - name: Tag latest version
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/getsentry/symbolicator:latest \
            ghcr.io/getsentry/symbolicator:${{ github.sha }}
